# Generated by Django 3.2.4 on 2021-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210702_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='number',
        ),
        migrations.AddField(
            model_name='transcription',
            name='line_number',
            field=models.IntegerField(default=0),
        ),
    ]
